### ISSUE TITLE
IO should not be instance of MonadPlus

### ISSUE THREAD

**Issue by safareli** [slamdata/purescript-io#3]
IO does not satisfies Distributivity law of MonadPlus:  `(x <|> y) >>= f == (x >>= f) <|> (y >>= f)`, see [Which satisfieswhat](https://wiki.haskell.org/MonadPlus#Which_satisfies_what.3F). IO is MonadOr which currently is not defined in `purescript-control`

**Comment by jdegoes** [comment]
Definitely should fix this!

**Comment by safareli** [comment]
I have created an issue to add MonadOr in [purescript-control#35](https://github.com/purescript/purescript-control/issues/35).
